### ISSUE TITLE
Can only use one extra bot token

### ISSUE THREAD

**Issue by CarterBrehm** [denverquane/automuteus#291]
```
automuteus_1  | 2020/11/25 05:32:04 error adding extra bot token to galactus: this token has already been added and recorded in Galactus
galactus_1    | 2020/11/25 05:32:04 Token already exists on the server
galactus_1    | 2020/11/25 05:32:04 Token already exists on the server
automuteus_1  | 2020/11/25 05:32:04 error adding extra bot token to galactus: this token has already been added and recorded in Galactus
galactus_1    | 2020/11/25 05:32:04 Token already exists on the server
automuteus_1  | 2020/11/25 05:32:04 error adding extra bot token to galactus: this token has already been added and recorded in Galactus
```

This is (what I think) the relevant section of my logs when I attempt to use one DISCORD_BOT_TOKEN and three WORKER_BOT_TOKENs. Only the main bot and one of the worker bots come online.

**Comment by CarterBrehm** [comment]
Hmm, not sure. I just downloaded the docker-compose.yml and the .env file a couple of days ago.

```
  galactus:
    ports:
      # See sample.env for details, but in general, match the GALACTUS_EXTERNAL_PORT w/ the GALACTUS_HOST's port
      - ${GALACTUS_EXTERNAL_PORT:-8123}:${BROKER_PORT}
    image: automuteus/galactus:${GALACTUS_TAG:-1.0.2}
```

Does this mean I have galactus 1.0.2?

**Comment by denverquane** [comment]
Yep, bump the version up to 1.0.3. But if it's specified in the .env as well, make sure it's updated there, too

**Comment by CarterBrehm** [comment]
That... seemed to work. Putting 1.0.3 didn't seem to work, so I just removed the version tag (I assumed that would pull the latest build) and everything's working properly.

```
  galactus:
    ports:
      # See sample.env for details, but in general, match the GALACTUS_EXTERNAL_PORT w/ the GALACTUS_HOST's port
      - ${GALACTUS_EXTERNAL_PORT:-8123}:${BROKER_PORT}
    image: automuteus/galactus
```
